### ISSUE TITLE
Advertising and wrong Vietnamese translations

### ISSUE THREAD

**Issue by JustAnyones** [TheoTown-Team/translations#662]
I did a surface scan of the Vietnamese translations searching for advertising as much as I could personally find and found the following occurrences of advertising or translation inconsistencies (meaning not the same as the default English strings).

Advertising, also ``topic_users`` is misleading.
https://github.com/TheoTown-Team/translations/blob/95763f00902c76cda5aba30f9ffdb8f96c1cd453/values-vi/strings.xml#L199-L208

Advertising
https://github.com/TheoTown-Team/translations/blob/95763f00902c76cda5aba30f9ffdb8f96c1cd453/values-vi/strings.xml#L213
https://github.com/TheoTown-Team/translations/blob/95763f00902c76cda5aba30f9ffdb8f96c1cd453/values-vi/strings.xml#L218
https://github.com/TheoTown-Team/translations/blob/95763f00902c76cda5aba30f9ffdb8f96c1cd453/values-vi/strings.xml#L461

Quotation? That's not what the original string is.
https://github.com/TheoTown-Team/translations/blob/95763f00902c76cda5aba30f9ffdb8f96c1cd453/values-vi/strings.xml#L1881

Missing mention of KolaKattz
https://github.com/TheoTown-Team/translations/blob/95763f00902c76cda5aba30f9ffdb8f96c1cd453/values-vi/strings.xml#L2593

**Comment by TA874** [comment]
https://github.com/TheoTown-Team/translations/pull/663/files
