### ISSUE TITLE
Italian translation problems

### ISSUE THREAD

**Issue by GamerPlayz200** [TheoTown-Team/translations#818]
In the road deco category, there are highway signs, wich can be select with the pole on the right, left or no pole (center).
If, in italian, you go to that, you'll see right is "Vero", wich, does not mean "Right", but means "True"; Instead, it should be "Destra"

In the "Interchange" category (Transport/Interchanges), In italian, it says "Interscambi"; It should be "Intercambi".

Some things, strangely, have "The" before their actual names, like "Il moderno departimento di polizia", wich would be "The modern police department", It should be just "Moderno departimento di polizia"

**Comment by Ree1352** [comment]
Just fork this repo, make required changes and create a pull request

**Comment by LobbyDivinus** [comment]
These were fixed in https://github.com/TheoTown-Team/translations/commit/00b929e889f426400942fe82151251cd61825859
